#!/usr/bin/env python3
"""Generate src/profinet_database.rs from the PNO XML database tables.

Usage: python3 databases/generate_database.py
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAN_ID = ROOT / "databases" / "Man_ID_Table.xml"
PROFILE_ID = ROOT / "databases" / "Profile_ID_Table.xml"
OUTPUT = ROOT / "src" / "profinet_database.rs"


def xml_text(path: Path) -> str:
    text = (ROOT / path).read_text(encoding="utf-8")
    return re.sub(r"<!--.*?-->", "", text, flags=re.S)


def escape(name: str) -> str:
    name = name.replace("\\", "\\\\").replace('"', '\\"')
    name = name.replace("\t", "\\t").replace("\r", "\\r").replace("\n", "\\n")
    return re.sub(r"[\x00-\x1f\x7f]", lambda m: f"\\u{{{ord(m.group(0)):04X}}}", name)


def main() -> None:
    manufacturers = []
    for block in re.finditer(
        r'<Manufacturer ID="(\d+)">(.*?)</Manufacturer>', xml_text(MAN_ID), flags=re.S
    ):
        match = re.search(r"<ManufacturerName>(.*?)</ManufacturerName>", block.group(2), flags=re.S)
        if not match:
            continue
        name = html.unescape(match.group(1)).strip()
        if name:
            manufacturers.append((int(block.group(1)), name))
    manufacturers.sort()
    if len(manufacturers) != len({entry[0] for entry in manufacturers}):
        raise SystemExit("duplicate manufacturer IDs in Man_ID_Table.xml")

    profiles = []
    for block in re.finditer(
        r'<Profile ID="(\d+)" EndID="(\d+)">(.*?)</Profile>', xml_text(PROFILE_ID), flags=re.S
    ):
        names = re.findall(r"<ProfileName[^>]*>(.*?)</ProfileName>", block.group(3), flags=re.S)
        english = re.search(
            r'<ProfileName xml:lang="en">(.*?)</ProfileName>', block.group(3), flags=re.S
        )
        name = html.unescape(english.group(1) if english else (names[0] if names else "")).strip()
        profiles.append((int(block.group(1)), int(block.group(2)), name))

    lines = [
        "// @generated by databases/generate_database.py from databases/Man_ID_Table.xml",
        "// and databases/Profile_ID_Table.xml. Do not edit; regenerate instead.",
        "",
        "#[rustfmt::skip]",
        "static MANUFACTURERS: &[(u16, &str)] = &[",
    ]
    lines.extend(f'    ({entry[0]}, "{escape(entry[1])}"),' for entry in manufacturers)
    lines.append("];")
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append("static PROFILES: &[(u32, u32, &str)] = &[")
    lines.extend(f'    ({entry[0]}, {entry[1]}, "{escape(entry[2])}"),' for entry in profiles)
    lines.extend(
        [
            "];",
            "",
            "pub(crate) fn manufacturer_name(id: u16) -> Option<&'static str> {",
            "    MANUFACTURERS",
            "        .binary_search_by_key(&id, |entry| entry.0)",
            "        .ok()",
            "        .map(|index| MANUFACTURERS[index].1)",
            "}",
            "",
            "pub(crate) fn profile_name(id: u16) -> Option<&'static str> {",
            "    PROFILES",
            "        .iter()",
            "        .find(|entry| u32::from(id) >= entry.0 && u32::from(id) <= entry.1)",
            "        .map(|entry| entry.2)",
            "}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
