services:
  siemens:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:102:102/tcp'
      - '${OTSERVER_LAB_BIND_IP}:161:161/udp'

  ethernet_ip:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:44818:44818/tcp'
      - '${OTSERVER_LAB_BIND_IP}:44818:44818/udp'

  bacnet:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:47808:47808/udp'

  fins:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:9600:9600/tcp'
      - '${OTSERVER_LAB_BIND_IP}:9600:9600/udp'

  fox:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:1911:1911/tcp'
      - '${OTSERVER_LAB_BIND_IP}:4911:4911/tcp'

  opcua:
    ports:
      - '${OTSERVER_LAB_BIND_IP}:4840:4840/tcp'
